- name: Install Packages
  ansible.builtin.dnf:
    name: [httpd,firewalld]
    state: present
- name: Copying index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
    owner: apache
    group: apache
    setype: httpd_sys_content_t
- name: Starting Services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd
    - firewalld
- name: Allowing HTTP Service over firewall
  ansible.posix.firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled

