---
- name: Playbook-1 Configuring balancer
  hosts: balancers
  gather_facts: true
  become: true
  roles:
    - balancer

- name: Playbook-2 Configuring phpinfo
  hosts: webservers
  gather_facts: true
  become: true
  roles:
    - phpinfo
