---
- name: Q11 - Playbook to manage Logical volume
  hosts: all
  gather_facts: true
  become: true
  vars:
    vg_name: research
    lv_name: data
    lv_size: 300M
    lv_alt_size: 200M
  tasks:
    - name: Check if "{{ vg_name }}" exists else show error
      ansible.builtin.fail:
        msg: "Volume group does not exists"
      when: ansible_facts['lvm']['vgs'][vg_name] is not defined
    - name: Managing Logical Volume
      block:
        - name: Creating logical volume of size "{{ lv_size }}"
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_size }}"
          register: lv_block
      rescue:
        - name: Error message
          ansible.builtin.debug:
            msg: "Could not create logical volume of that size"

        - name: Creating logical volume of size "{{ lv_alt_size }}"
          community.general.lvol:
            vg: "{{ vg_name }}"
            lv: "{{ lv_name }}"
            size: "{{ lv_alt_size }}"
          register: lv_rescue
      always:
        - name: Creating File systems
          community.general.filesystem:
            fstype: ext4
            dev: "/dev/{{ vg_name }}/{{ lv_name }}"
            force: true
          when: ( lv_block is defined and lv_block.changed ) or ( lv_rescue is defined and lv_rescue.changed )
