---
- name: Q13 - Playbook Managing webcontent
  hosts: dev
  gather_facts: true
  become: true
  tasks:
    - name: Creating webdev group
      ansible.builtin.group:
        name: webdev
        state: present
    - name: Installing required packages
      ansible.builtin.dnf:
        name: [httpd,firewalld]
        state: present
    - name: Start and enable services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld
    - name: Creating Webdev directory
      ansible.builtin.file:
        state: directory
        path: /webdev
        owner: apache
        group: webdev
        mode: '2775'
        setype: httpd_sys_content_t
    - name: Creating index.html
      ansible.builtin.copy:
        content: Development
        dest: /webdev/index.html
        mode: '0644'
        owner: apache
        setype: httpd_sys_content_t
    - name: Creating symlink for webdev
      ansible.builtin.file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
        owner: apache
        group: apache
    - name: Allowing http service
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
