---
- name: Q17 - playbook to configure cron
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Creating user if not exists
      ansible.builtin.user:
        name: student
        state: present
    - name: Configuring cron job
      ansible.builtin.cron:
        name: ex294_job
        user: student
        job: logger "EX294 in progress"
        minute: "*/2"
