---
- name: Q18 - Playbook to manage partitions
  hosts: test,prod
  gather_facts: true
  become: true
  tasks:
    - name: Handling Partition creation
      block:
        - name: Creating partition on vdb of size 1500M
          community.general.parted:
            device: /dev/vdb
            number: 1
            part_type: primary
            part_end: 1500MB
            state: present
          register: lv_1500
      rescue:
        - name: Error message for insufficient space
          ansible.builtin.debug:
            msg: "Could not create partition of that size"

        - name: Creating partition on vdb of size 800M
          community.general.parted:
            device: /dev/vdb
            number: 1
            part_type: primary
            part_end: 800MB
            state: present
          register: lv_800
      
      always:
        - name: Creating Filesystem
          ansible.builtin.filesystem:
            dev: /dev/vdb1
            fstype: ext4
            force: true
          when: ( lv_1500 is defined and lv_1500.changed ) or ( lv_800 is defined and lv_800.changed )
          register: fs_stat
        - name: Creating mount point if not exists
          ansible.builtin.file:
            state: directory
            path: /part1
          when: fs_stat is not skipped 
        - name: Mouting Filesystem
          ansible.posix.mount:
            path: /part1
            src: /dev/vdb1
            fstype: ext4
            state: mounted
          when: 
            - ( lv_1500 is defined and lv_1500.changed ) or ( lv_800 is defined and lv_800.changed )
            - fs_stat is not skipped
    - name: Checking if /dev/vdd is exists else throw error
      ansible.builtin.debug:
        msg: "Disk does not exists"
      when: ansible_facts['devices']['vdd'] is not defined

