---
- name: Q19 - Playbook to manage SELInux
  hosts: all
  become: true
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
  tasks:
    - name: Enabling SELinux on all nodes
      ansible.builtin.import_role:
        name: rhel-system-roles.selinux

