---
- name: Playbook 1 To install PHP and MariaDB
  hosts: dev,test,prod
  become: true
  gather_facts: false
  tasks:
    - name: Install Packages
      ansible.builtin.dnf:
        name: [php,mariadb]
        state: present

- name: Playbook 2 To install RPM Tools and patching
  hosts: dev
  become: true
  gather_facts: false
  tasks:
    - name: Install RPM Tools
      ansible.builtin.dnf:
        name: "@RPM Development Tools"
        state: present

    - name: Upgrade packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

